---
- name: Configurer les ACL sur le switch Cisco
  hosts: RT-TL
  gather_facts: no

  tasks:
    - name: Configurer une ACL
      ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: 101
                aces:
                  - grant: permit
                    protocol_options:
                      icmp:
                        traceroute: true
                    source:
                      address: 10.99.1.0
                      wildcard_bits: 0.0.0.255
                    destination:
                      address: 172.16.1.0
                      wildcard_bits: 0.0.0.255
        state: merged
