---
- name: Enregistrer la configuration
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Get Configuration
      cisco.ios.ios_command:
        commands: show run
      register: config

    - name: Save it in file
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "/home/sio/{{ inventory_hostname }}_config.txt"
