---
- name: Création d'un VLAN sur le switch Cisco
  hosts: switches
  gather_facts: no

  tasks:
    - name: Création VLAN Test ID 299
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_Test2
            vlan_id: 299
            state: active
            shutdown: disabled

    - name: Affecter VLAN 299 à l'interface FastEthernet0/1
      cisco.ios.ios_config:
        lines:
          - switchport access vlan 299
        parents: interface FastEthernet0/13
